# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tiny Bits Of Carbon
description: >- # this means to ignore newlines until "baseurl:"
  A blog about a lot of things that possibly amount to nothing
baseurl: "" # the subpath of your site, e.g. /blog
logo: /assets/images/carbon.svg
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
name: Aamna
twitter_username: _aamnakhan
github_username:  aamnakhan


#pagination
paginate: 2s
paginate_path: "/page/:num/"

defaults:
 #posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      share: true
      related: true
  #pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-44949721-3"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: contrast
locale: en
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

whitelist:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache


include: ["_pages", "_posts"]

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
